{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "taskapi.fullname" . }}-migrate
  labels:
    {{- include "taskapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 180
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "taskapi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "taskapi.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - src/infrastructure/database/migrate.js
          env:
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.migrationExistingSecret }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
{{- end }}
